# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='p_id',
            field=models.CharField(default=7567546712, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='my_file',
            field=models.ImageField(upload_to=polls.models.upload_to),
        ),
    ]
