# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170720_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
