# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_file_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to=polls.models.upload_to)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.CSVFile')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
